AvdLee/Diagnostics

Changelog.md
Diagnostics.xcodeproj/project.pbxproj
Diagnostics/Info.plist
Sources/Reporters/GeneralInfoReporter.swift
Sources/Reporters/UserDefaultsReporter.swift

Had to import Foundation.
Also bumped version to 1.0.1
Fixes #15

Fix SPM build errors

---

Changelog.md
Diagnostics.podspec

CSS file was not included in the bundle.
Fixes #21

Fixes CocoaPods CSS error

---

Changelog.md
Sources/DiagnosticsReport.swift

As saving might otherwise fail.

Make sure the folder for saving to desktop exists

---

Changelog.md
Diagnostics.podspec
Diagnostics.xcodeproj/project.pbxproj
Sources/DiagnosticsReporter.swift
Sources/style.css

The CSS resource file was not getting included for SPM. We now moved the CSS inline.
Fixes #28

Fix SPM support by removing resources

---

Changelog.md
Sources/DiagnosticsLogger.swift

New feature: Added public static func `DiagnosticsLogger.isSetUp()` that returns the value of var `DiagnosticsLogger.standard.isSetUp` (#41). Could be useful for development and debugging.

Added public static func `DiagnosticsLogger.isSetUp()`

---

Changelog.md
Package.swift

Update for #43 
Thanks @davidsteppenbeck for pointing out 👍

Update package.swift to iOS 10.0.

---

.gitmodules
Diagnostics.podspec

Fix warning occurring in pod library because of importing style.css #trivial

---

DiagnosticsTests/Reporters/LogsReporterTests.swift
Sources/DiagnosticsLogger.swift
Sources/Reporters/LogsReporter.swift

This will help us to more easily diggest reports.
Fixes #54

Change the order of the report

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.5.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.5.0).

Merge release 1.5.0 into master

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.7.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.7.0).

Merge release 1.7.0 into master

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.8.1 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.8.1).

Merge release 1.8.1 into master

---

README.md

We didn't describe that we support Swift Package Manager.

Update readme to include SPM

---

Package.swift

A little Package maintenance update. Also, we can statically link this for better launch performance.

Package is now static and uses swift tools 5.3

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.9.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.9.0).

Merge release 1.9.0 into master

---

Changelog.md
Diagnostics.podspec
Gemfile.lock

Containing all the changes for our [**1.9.1 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.9.1).

Merge release 1.9.1 into master

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.10.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.10.0).

Merge release 1.10.0 into master

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**2.0.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/2.0.0).

Merge release 2.0.0 into master

---

Changelog.md

Containing all the changes for our [**3.0.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/3.0.0).

Merge release 3.0.0 into master

---

DiagnosticsTests/Reporters/DirectoryTree/DirectoryTreeFactoryTests.swift
DiagnosticsTests/Reporters/LogsReporterTests.swift
Example/Diagnostics-Example.xcodeproj/project.pbxproj
Example/Diagnostics-Example/Supporting Files/AppDelegate.swift
Example/Diagnostics-Example/Supporting Files/SceneDelegate.swift
Sources/Device.swift
Sources/DiagnosticsReport.swift
Sources/DiagnosticsReportFilter.swift
Sources/DiagnosticsReporter.swift
Sources/HTMLEncoding.swift
Sources/HTMLGenerating.swift
Sources/Logging/DiagnosticsLogger.swift
Sources/Logging/Loggable.swift
Sources/Reporters/DirectoryTree/DirectoryTreeFactory.swift
Sources/Reporters/DirectoryTree/DirectoryTreeNode.swift
Sources/Reporters/DirectoryTree/DirectoryTreeStringFactory.swift
Sources/Reporters/GeneralInfoReporter.swift
Sources/SmartInsights/DeviceStorageInsight.swift
Sources/SmartInsights/UpdateAvailableInsight.swift

SwiftLint didn't execute yet for this project, so I re-enabled it and ensured all warnings were fixed.

Re-configure SwiftLint and fix warnings

---

Changelog.md

Containing all the changes for our [**4.1.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/4.1.0).

Merge release 4.1.0 into master

---

Sources/Device.swift
Sources/Logging/DiagnosticsLogger.swift
Sources/Reporters/AppSystemMetadataReporter.swift
Sources/Reporters/SmartInsightsReporter.swift
Sources/SmartInsights/CellularAllowedInsight.swift
fastlane/Fastfile

Making sure Diagnostics still builds for macOS. Also fixing CI!

Fix macOS support

---

Example/Diagnostics-Example/ViewController.swift
Package.resolved
Sources/Logging/Loggable.swift

Even though it's not greatly readable:
It's better than nothing. Critical crashes could be solved by parsing the JSON on a site like jsonlint.com and make it more readable. One needs to symbolicate the threads and addresses, but having these is better than nothing and gives us a start for difficult to solve crashes.
```json
{
"callStacks": [{
"threadAttributed": true,
"callStackRootFrames": [{
"offsetIntoBinaryTextSegment": 45408,
"address": 7895789920,
"sampleCount": 1,
"subFrames": [{
"offsetIntoBinaryTextSegment": 29100,
"address": 8171651500,
"sampleCount": 1,
"subFrames": [{
"offsetIntoBinaryTextSegment": 134284,
"address": 6986943628,
"sampleCount": 1,
"subFrames": [{
"offsetIntoBinaryTextSegment": 72588,
"address": 8170863500,
"sampleCount": 1,
"subFrames": [{ …
```

Add JSON data around crash callstack

---

Changelog.md

Containing all the changes for our [**4.4.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/4.4.0).

Merge release 4.4.0 into master

---

Changelog.md

Containing all the changes for our [**4.6.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/4.6.0).

Merge release 4.6.0 into master

---

README.md

This PR fixes a typo by rewording the sentence altogether.

Reword `Using a UserDefaultsReporter` section

---

Changelog.md

Update changelog for `5.0.0` release.

Update changelog for `5.0.0` release

---

Package@swift-5.5.swift
Package@swift-5.6.swift
Package@swift-5.7.swift
Package@swift-5.8.swift

This Pull Request adds visionOS support while keeping support to Swift 5.5
Fixes #162.

Add visionOS support

---

README.md

Added a section listing projects that use Roadmap.

Add projects using Roadmap to README
