AvdLee/Diagnostics

Sources/Extensions/UIDeviceExtensions.swift

The following PR will fix the issue with 
`if let space = try? URL(fileURLWithPath: NSHomeDirectory() as String).resourceValues(forKeys: [URLResourceKey.volumeAvailableCapacityForImportantUsageKey]).volumeAvailableCapacityForImportantUsage` is still an resolving into an optional in swift 4.2 whereas swift 5 it's a normal Uint64

Adds swift 4.0 support to the framework

---

Changelog.md
Sources/DiagnosticsLogger.swift

It turned out that the `Pipe` we were using to capture any `STDOUT_FILENO` output was also capturing xcodebuild output. This caused our Fastlane setup to fail. We had to forward the output to an outpipe to make sure original logs show up again.
This is to make sure that the logs are showing up in the Xcode console while debugging but as well for runs in the terminal when testing.
More info in this blog post: https://medium.com/@thesaadismail/eavesdropping-on-swifts-print-statements-57f0215efb42

Forward the output of the DiagnosticsLogger to not disable default logging

---

Changelog.md
Diagnostics.podspec
Diagnostics.xcodeproj/project.pbxproj
Sources/Reporters/UserDefaultsReporter.swift

Changelog
1. make minimum deployment to iOS 10.0 to podspec.
2. Json serialization sortedKeys options remove for iOS 10.
Fixes #42

min deployment target iOS 10.0

---

Changelog.md
Sources/DiagnosticsLogger.swift

There is currently no indication of AM or PM in the log times, so I changed the the logger's date formatter to use a 24H clock.

Changed log times to use 24H clock.

---

Changelog.md
Sources/DiagnosticsLogger.swift

This fixes crashes happening for users that don't have enough space left on their device.
Fixes #37

Check available disk space before writing to the log

---

Changelog.md
Sources/DiagnosticsReporter.swift

Non-ascii characters in HTML output were not displayed correctly in Safari. Specifying charset to utf-8 in HTML meta tag will fix this issue.

Add charset utf-8 to html head

---

Changelog.md
Diagnostics.xcodeproj/project.pbxproj
Sources/HTMLEncoding.swift
Sources/Reporters/LogsReporter.swift

Adds HTML encoding to logged strings when final report is created.
Fixes #51

Encode HTML in final report

---

Sources/Reporters/AppSystemMetadataReporter.swift

Only includes most recent iPhone models.
Fixes #60

Add product names to report metadata.

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.6.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.6.0).

Merge release 1.6.0 into master

---

Example/Diagnostics-Example.xcodeproj/xcshareddata/xcschemes/Diagnostics-Example.xcscheme
Sources/DiagnosticsLogger.swift

In the process of fixing #65 I've been optimizing our code a bit.
| Before | After |
| --- | --- |
| <img width="504" alt="Screenshot 2020-05-25 at 16 02 25" src="https://user-images.githubusercontent.com/4329185/82820236-1c01ec00-9ea2-11ea-8d14-fb70661ed943.png"> | <img width="520" alt="Screenshot 2020-05-25 at 16 02 09" src="https://user-images.githubusercontent.com/4329185/82820235-1a382880-9ea2-11ea-9580-c8892a6fee7d.png"> |
Fixes #65

Fix memory leak in readInBackgroundAndNotify method

---

README.md
Sources/Device.swift
Sources/DiagnosticsLogger.swift
Sources/Extensions/BundleExtensions.swift
Sources/Extensions/ByteCountFormatter.swift
Sources/MFMailExtensions/MFMailComposeVCExtensions.swift
Sources/Reporters/AppSystemMetadataReporter.swift

Hi, first of all: thank you for this awesome framework! 🙂 
I want to use it with a non-catalyst app and added a [`enum Device`](https://github.com/JulianKahnert/Diagnostics/blob/master/Sources/Device.swift) that wraps the os specific information.
What do you think of this solution?

native (aka non-catalyst) macOS support added

---

Changelog.md
Diagnostics.podspec

Containing all the changes for our [**1.8.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/1.8.0).

Merge release 1.8.0 into master

---

Diagnostics.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
DiagnosticsTests/Reporters/LogsReporterTests.swift
Sources/DiagnosticsLogger.swift

I've looked at other logging implementation, like [SwiftyBeaver](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/fb468e5e3184f7e041ba46e5bfd0fc1670846eb6/Sources/FileDestination.swift#L114) and figured we could do a better job in terms of writing performance. Also, it seemed that certain logs weren't written when the app was in the background. The changes in this PR increase chances of logs ending up in the reports by closing the file handle right after writing.

Prevent setup twice, use file coordinator for increased performance

---

Sources/DiagnosticsLogger.swift

We used to use the `write(_:)` method which has the following documentation:
> This method raises an exception if the file descriptor is closed or is not valid, if the receiver represents an unconnected pipe or socket endpoint, if no free space is left on the file system, or if any other writing error occurs. 
This resulted in several crashes for users which storage was full. With this PR, we fix the crash for users on iOS 13.4 and up which seems good enough for now.

Use latest write APIs to prevent a crash when storage is full.

---

.swiftpm/xcode/xcshareddata/xcschemes/Diagnostics.xcscheme
DiagnosticsTests/DiagnosticsReporterTests.swift
Example/Diagnostics-Example/Supporting Files/AppDelegate.swift
Package.swift
Sources/DiagnosticsReporter.swift
Sources/Extensions/DateFormatterExtensions.swift
Sources/Logging/DiagnosticsLogger.swift
Sources/Logging/Loggable.swift
Sources/MetricKit/MetricsMonitor.swift
Sources/Reporters/LogsReporter.swift
Sources/functions.js
Sources/style.css

This is our first major improvement of the Diagnostics report we've been using for more than a year now at WeTransfer. Based on our experience, these changes are needed to make it easier to find out what's wrong with the user that reported in.
The main goal of these changes is to speed up the time from a bug report to a fix. 🚀 
- Added filter options to hide system, errors, and debug logs (Fixes #96, Fixes #82)
- Added buttons to collapse/expand all sessions (Fixes #101, Fixes #95)
- Added CSS for errors to show them with a red background to easily find errors in logs
- Proper support for logging HTML links by no longer using `<pre>` (Fixes #102)
- Fixed CSS for links (Fixes #100)
- Using SPM resources instead of inline CSS and Javascript, allowing us to maintain CSS and JS in individual …

Diagnostics 2.0

---

Sources/Logging/DiagnosticsLogger.swift
Sources/Logging/Loggable.swift

Using StaticString since that's more correct

---

Example/Diagnostics-Example/Supporting Files/AppDelegate.swift
Sources/Logging/Loggable.swift
Sources/style.css

Long text would not easily be readable since it requires us to scroll horizontally. This is a quick win that will improve readability

Wrap words for better readability

---

Example/Diagnostics-Example/CustomSmartInsights.swift
README.md

Hey there, thanks for making Diagnostics public, I think it's a cool way to debug apps in production. 
I saw that you had a discussion about whether to use an optional array or just an empty array (https://github.com/WeTransfer/Diagnostics/pull/113/commits/e75d7e4a1d9ad647552195d6aa5b3ecbe2d79464) and decided to go the non-optional way. It seems though that you forgot to change the example, so that's what this pull request is.

Update example and readme

---

Package.swift
Sources/Logging/DiagnosticsLogger.swift

FileHandles can potentially throw exceptions that aren't catchable by Swift. I experienced this by detaching/attaching the debugger. I decided to add a small dependency to catch this and at least prevent apps from crashing. 
Another small improvement removes an unnecessary dispatch since we dispatch again within the following method.

Catch obj-c exception, remove unneeded dispatch

---

Sources/Logging/DiagnosticsLogger.swift
Sources/Logging/Loggable.swift

I am wrapping `DiagnosticsLogger` inside a `LogHandler` from [swift-log](https://github.com/apple/swift-log) package so that I can use swift-log as the main logger for my app. 
But currently, Diagnostics is using StaticString for #file, #line, #function in the `log` method
[swift-log](https://github.com/apple/swift-log/blob/3577a992d373d0e7f75d1fdc6e6e4570b60a1e1f/Sources/Logging/LogHandler.swift#L129) is using `String` instead of `StaticString` for #file, #line, #function 
I think, changing `StaticString` to `String` would make it more interoperable with swift-log and provides more flexibility to integrate with other libraries as well.

Use String instead of StaticString to be more inline with swift-log behaviour

---

Changelog.md

Containing all the changes for our [**4.0.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/4.0.0).

Merge release 4.0.0 into master

---

Sources/Reporters/AppSystemMetadataReporter.swift
Sources/Reporters/SmartInsightsReporter.swift
Sources/SmartInsights/CellularAllowedInsight.swift

Found this a quick fix. It might give us insights into why transfers fail: system-wide mobile data disabled.
Also added it as a smart insight:

Report whether cellular is allowed

---

DiagnosticsTests/Reporters/LogsReporterTests.swift
Example/Diagnostics-Example/Supporting Files/AppDelegate.swift
Sources/Logging/Loggable.swift

We supported printing HTML in logs, but that often resulted in our Diagnostics reports breaking since nothing was stopping users from printing `<link ...css>` as well.
I tried writing a solution to enable certain tags like `<a>` for example, but I couldn't find a solution without adding an extra dependency to the project. I decided it's not worth adding that for now and instead ensured all HTML is encoded.
Fixes #120

Fix HTML encoding

---

Sources/Device.swift
Sources/Logging/DiagnosticsLogger.swift

Running Diagnostics on iOS 16 resulted in a deadlock since checking for system available space results in system logs being triggered on iOS 16 and up. Since we capture system logs, we would try to log them again, check for system space, triggering another system log. Since we capture system logs, we would try to log them again, check for system space, triggering another system log. Since we capture system logs, we would try to log them again, check for system space, triggering another system log. Since we capture system logs, we would try to log them again, check for system space, triggering another system log.
I added a threshold to ensure that we only check for free disk space periodically, solving this issue.
Furthermore:

Fix infinite loop happening on iOS 16 devices

---

Changelog.md

Containing all the changes for our [**4.2.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/4.2.0).

Merge release 4.2.0 into master

---

Sources/Reporters/AppSystemMetadataReporter.swift
Sources/Reporters/SmartInsightsReporter.swift
Sources/SmartInsights/CellularAllowedInsight.swift

Because [`CTCellularData`](https://developer.apple.com/documentation/coretelephony/ctcellulardata) is unavailable for macCatalyst, I added `!targetEnvironment(macCatalyst)` to the already existing `#if os(iOS)` checks.

Fix macCatalyst support

---

Sources/DiagnosticsReporter.swift
Sources/Reporters/SmartInsightsReporter.swift
Sources/SmartInsights/UpdateAvailableInsight.swift

Hi,
just started using this library in one of my apps and noticed the report doesn't includes the update available smart insights because my app is only available in Spain and it tries to retrieve metadata from Brazilian App Store.
In this PR I include an optional parameter to set the iTunes region in the create report method. Also including the option to set custom report filename.
Congratulations for this great package.

Let developer set App Store region for UpdateAvailableInsight

---

Sources/Reporters/DirectoryTree/DirectoryTreeReporter.swift

proposing something like this (or better & complete) to have all properties of directory like includeHiddenFiles, maxDepth etc. ik this is quite a big change and would not be backward compatible but i guess worth to include something similar.
your thoughts on this?  @AvdLee

directory modelling suggestion

---

DiagnosticsTests/Extensions/MFMailComposeViewControllerTests.swift
DiagnosticsTests/Reporters/SmartInsights/UpdateAvailableInsightTests.swift
Package.swift
Sources/Reporters/SmartInsightsReporter.swift
Sources/SmartInsights/UpdateAvailableInsight.swift

We would like to integrate this great package into our app but our app is still supporting iOS 11+.
It looks like that the main functionality of the package is available for iOS 11, only a default SmartInsight requires iOS 13+ due to Combine
I have added some availability checks for that SmartInsight and set the minimum iOS platform version to 11.

Set minimum iOS support to iOS 11

---

DiagnosticsTests/DiagnosticsReporterTests.swift
Sources/DiagnosticsChapter.swift
Sources/DiagnosticsReport.swift
Sources/HTMLGenerating.swift
Sources/Reporters/DirectoryTree/DirectoryTreeNode.swift

Adds `Sendable` conformance to our types that aren't mutable.

Add Sendable conformance

---

Sources/Logging/Loggable.swift

#149
Updated the logDescription of the MXCrashDiagnostic to print the human-readable lookups for the exception type and signals defined in iOS SDK header files using custom string interpolations.

Updated logDescription of MXCrashDiagnostic with human-readable exception type and signal

---

Changelog.md

Containing all the changes for our [**4.5.0 Release**](https://github.com/WeTransfer/Diagnostics/releases/tag/4.5.0).

Merge release 4.5.0 into master

---

Sources/DiagnosticsReport.swift
Sources/Reporters/AppSystemMetadataReporter.swift
Sources/SmartInsights/CellularAllowedInsight.swift

When building for the VisionOS simulator, Xcode throws errors on availability of `CoreTelephony`. This PR conditionally imports `CoreTelephony`.

Fix: unblock building for VisionOS Simulator

---

Example/Diagnostics-Example/Supporting Files/AppDelegate.swift
Sources/DiagnosticsReporter.swift
Sources/Logging/Loggable.swift
Sources/Reporters/GeneralInfoReporter.swift

Fix SwiftLint warnings inside example project

---

Example/Diagnostics-Example/Supporting Files/AppDelegate.swift
Sources/DiagnosticsReporter.swift
Sources/Logging/DiagnosticsLogger.swift
Sources/Logging/Loggable.swift
Sources/Reporters/GeneralInfoReporter.swift
Sources/Reporters/LogsReporter.swift

There have been instances where logs wouldn't be readable, failing with:
```
Parsing the log failed
```
Since we did not log any related failures, it's hard to conclude what went wrong. This PR enables logging thrown errors so we can better debug this in the future.
_Note: often a regeneration/retry solved the issue for users._

[TMOB 5114] Log failures happening during log reading

---

DiagnosticsTests/Reporters/LogsReporterTests.swift
DiagnosticsTests/Reporters/LogsTrimmerTests.swift
Sources/Logging/DiagnosticsLogger.swift
Sources/Logging/Loggable.swift
Sources/Logging/LogsTrimmer.swift

We found several broken Diagnostics reports where the HTML would not longer be valid. This turned out to be caused by our trimmer which trimmed based on byte size rather than looking at HTML components. 
This PR fixes this by removing N number of lines when the log size is too big.

[TMOB 5115] Trim using lines instead of bytes

---

DiagnosticsTests/Reporters/AppSystemMetadataReporterTests.swift
DiagnosticsTests/Reporters/UserDefaultsReporterTests.swift
Package.swift
Sources/DiagnosticsReporter.swift
Sources/PrivacyInfo.xcprivacy
Sources/Reporters/AppSystemMetadataReporter.swift
Sources/Reporters/UserDefaultsReporter.swift

This PR adds a privacy manifest file and makes a few improvements along the way.
This is a breaking change around `UserDefaultsReporter`, making sure that we are using it matching the privacy requirements. Because of these changes, `UserDefaultsReporter` is not part of the `DefaultReporter.allReporters`, requiring for users of the library to instantiate a `UserDefaultsReporter` themselves if they would like to use this reporter.
The main change is on how we're using `UserDefaultsReporter` internally to use `UserDefaults`. We decided to keep `UserDefaultsReporter` to make it less of a breaking change to the developers using `Diagnostics`, instead of removing it completely.
Before the changes, we were using the `dictionaryRepresentation()` in the `UserDefaults` instance, which would return …

Add Privacy Manifest

---

README.md

This PR updates the `README` file with the `UserDefaultsReporter` changes from https://github.com/WeTransfer/Diagnostics/pull/171.
Part of [TMOB-5314](https://wetransfer.atlassian.net/browse/TMOB-5314), #157 and #168.
[TMOB-5314]: https://wetransfer.atlassian.net/browse/TMOB-5314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update README with the `UserDefaultsReporter` changes
